---
title: "ReadCSV_Excelfiles"
author: "codewithbiologits"
output: html_document
date: "2026-03-06"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#=================================================
# How to read multiple csv file 
#=================================================


#===============================
# 1 load libraries 
#===============================

```{r}
library(tidyverse)
library(readr)
library(readxl)
library(purrr)
library(janitor)

```















#===============================
# 2 set path to data folder 
#===============================
```{r}
csv_files <- list.files(
  path = "multi_csv/",
  pattern = "*.csv",
  full.names = TRUE
)
csv_files
```
















#================================================
# 3 Read all the file & append data 
# (important- Header must be same in each file)
#================================================

```{r}
data_combined <- csv_files %>%
  purrr::map_dfr(~ readr::read_csv(.x,
            col_types = cols(.default = "c")),
          .id = "file_id") %>%
    type_convert() %>% 
  janitor::clean_names() 

data_combined
```


##### END ####































































































